server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.wasm$ {
        default_type application/wasm;
        try_files $uri =404;
    }

    location ~* \.pck$ {
        default_type application/octet-stream;
        try_files $uri =404;
    }

    gzip on;
    gzip_types
        text/plain
        text/css
        application/javascript
        application/wasm
        application/octet-stream;
}