extends RefCounted
class_name TowerVisualRegistry

# Lookup order:
#   1. BY_ID   — exact tower_id match → scripts/towers/visuals/by_id/<id>_visual.gd
#   2. VISUALS — visual_type family   → scripts/towers/visuals/fallback/<type>_tower_visual.gd
#   3. "basic" fallback               → fallback/basic_tower_visual.gd
#
# Every visible tower in the catalog has a BY_ID entry.
# Custom redesigns live in by_id/. Wrappers delegate to fallback/.
# Add a new tower: create by_id/<tower_id>_visual.gd, then add it here.

# Per-tower-id visual files. One entry per visible tower.
const BY_ID := {
	"basic_tower_t1": preload("res://scripts/towers/visuals/by_id/basic_tower_t1_visual.gd"),
	"blacksmith_t1": preload("res://scripts/towers/visuals/by_id/blacksmith_t1_visual.gd"),
	"blacksmith_t2": preload("res://scripts/towers/visuals/by_id/blacksmith_t2_visual.gd"),
	"blacksmith_t3": preload("res://scripts/towers/visuals/by_id/blacksmith_t3_visual.gd"),
	"corrosion_t1": preload("res://scripts/towers/visuals/by_id/corrosion_t1_visual.gd"),
	"corrosion_t2": preload("res://scripts/towers/visuals/by_id/corrosion_t2_visual.gd"),
	"corrosion_t3": preload("res://scripts/towers/visuals/by_id/corrosion_t3_visual.gd"),
	"darkness_t1": preload("res://scripts/towers/visuals/by_id/darkness_t1_visual.gd"),
	"darkness_t2": preload("res://scripts/towers/visuals/by_id/darkness_t2_visual.gd"),
	"darkness_t3": preload("res://scripts/towers/visuals/by_id/darkness_t3_visual.gd"),
	"disease_t1": preload("res://scripts/towers/visuals/by_id/disease_t1_visual.gd"),
	"disease_t2": preload("res://scripts/towers/visuals/by_id/disease_t2_visual.gd"),
	"disease_t3": preload("res://scripts/towers/visuals/by_id/disease_t3_visual.gd"),
	"drowning_t1": preload("res://scripts/towers/visuals/by_id/drowning_t1_visual.gd"),
	"drowning_t2": preload("res://scripts/towers/visuals/by_id/drowning_t2_visual.gd"),
	"drowning_t3": preload("res://scripts/towers/visuals/by_id/drowning_t3_visual.gd"),
	"earth_t1": preload("res://scripts/towers/visuals/by_id/earth_t1_visual.gd"),
	"earth_t2": preload("res://scripts/towers/visuals/by_id/earth_t2_visual.gd"),
	"earth_t3": preload("res://scripts/towers/visuals/by_id/earth_t3_visual.gd"),
	"electricity_t1": preload("res://scripts/towers/visuals/by_id/electricity_t1_visual.gd"),
	"electricity_t2": preload("res://scripts/towers/visuals/by_id/electricity_t2_visual.gd"),
	"electricity_t3": preload("res://scripts/towers/visuals/by_id/electricity_t3_visual.gd"),
	"enchantment_t1": preload("res://scripts/towers/visuals/by_id/enchantment_t1_visual.gd"),
	"enchantment_t2": preload("res://scripts/towers/visuals/by_id/enchantment_t2_visual.gd"),
	"enchantment_t3": preload("res://scripts/towers/visuals/by_id/enchantment_t3_visual.gd"),
	"fire_t1": preload("res://scripts/towers/visuals/by_id/fire_t1_visual.gd"),
	"fire_t2": preload("res://scripts/towers/visuals/by_id/fire_t2_visual.gd"),
	"fire_t3": preload("res://scripts/towers/visuals/by_id/fire_t3_visual.gd"),
	"flame_t1": preload("res://scripts/towers/visuals/by_id/flame_t1_visual.gd"),
	"flame_t2": preload("res://scripts/towers/visuals/by_id/flame_t2_visual.gd"),
	"flame_t3": preload("res://scripts/towers/visuals/by_id/flame_t3_visual.gd"),
	"flamethrower_t1": preload("res://scripts/towers/visuals/by_id/flamethrower_t1_visual.gd"),
	"flamethrower_t2": preload("res://scripts/towers/visuals/by_id/flamethrower_t2_visual.gd"),
	"flamethrower_t3": preload("res://scripts/towers/visuals/by_id/flamethrower_t3_visual.gd"),
	"flesh_golem_t1": preload("res://scripts/towers/visuals/by_id/flesh_golem_t1_visual.gd"),
	"flesh_golem_t2": preload("res://scripts/towers/visuals/by_id/flesh_golem_t2_visual.gd"),
	"flesh_golem_t3": preload("res://scripts/towers/visuals/by_id/flesh_golem_t3_visual.gd"),
	"gold_t1": preload("res://scripts/towers/visuals/by_id/gold_t1_visual.gd"),
	"gold_t2": preload("res://scripts/towers/visuals/by_id/gold_t2_visual.gd"),
	"gold_t3": preload("res://scripts/towers/visuals/by_id/gold_t3_visual.gd"),
	"gunpowder_t1": preload("res://scripts/towers/visuals/by_id/gunpowder_t1_visual.gd"),
	"gunpowder_t2": preload("res://scripts/towers/visuals/by_id/gunpowder_t2_visual.gd"),
	"gunpowder_t3": preload("res://scripts/towers/visuals/by_id/gunpowder_t3_visual.gd"),
	"hail_t1": preload("res://scripts/towers/visuals/by_id/hail_t1_visual.gd"),
	"hail_t2": preload("res://scripts/towers/visuals/by_id/hail_t2_visual.gd"),
	"hail_t3": preload("res://scripts/towers/visuals/by_id/hail_t3_visual.gd"),
	"hydro_t1": preload("res://scripts/towers/visuals/by_id/hydro_t1_visual.gd"),
	"hydro_t2": preload("res://scripts/towers/visuals/by_id/hydro_t2_visual.gd"),
	"hydro_t3": preload("res://scripts/towers/visuals/by_id/hydro_t3_visual.gd"),
	"ice_t1": preload("res://scripts/towers/visuals/by_id/ice_t1_visual.gd"),
	"ice_t2": preload("res://scripts/towers/visuals/by_id/ice_t2_visual.gd"),
	"ice_t3": preload("res://scripts/towers/visuals/by_id/ice_t3_visual.gd"),
	"impulse_t1": preload("res://scripts/towers/visuals/by_id/impulse_t1_visual.gd"),
	"impulse_t2": preload("res://scripts/towers/visuals/by_id/impulse_t2_visual.gd"),
	"impulse_t3": preload("res://scripts/towers/visuals/by_id/impulse_t3_visual.gd"),
	"jinx_t1": preload("res://scripts/towers/visuals/by_id/jinx_t1_visual.gd"),
	"jinx_t2": preload("res://scripts/towers/visuals/by_id/jinx_t2_visual.gd"),
	"jinx_t3": preload("res://scripts/towers/visuals/by_id/jinx_t3_visual.gd"),
	"laser_t1": preload("res://scripts/towers/visuals/by_id/laser_t1_visual.gd"),
	"laser_t2": preload("res://scripts/towers/visuals/by_id/laser_t2_visual.gd"),
	"laser_t3": preload("res://scripts/towers/visuals/by_id/laser_t3_visual.gd"),
	"life_t1": preload("res://scripts/towers/visuals/by_id/life_t1_visual.gd"),
	"life_t2": preload("res://scripts/towers/visuals/by_id/life_t2_visual.gd"),
	"life_t3": preload("res://scripts/towers/visuals/by_id/life_t3_visual.gd"),
	"light_t1": preload("res://scripts/towers/visuals/by_id/light_t1_visual.gd"),
	"light_t2": preload("res://scripts/towers/visuals/by_id/light_t2_visual.gd"),
	"light_t3": preload("res://scripts/towers/visuals/by_id/light_t3_visual.gd"),
	"magic_t1": preload("res://scripts/towers/visuals/by_id/magic_t1_visual.gd"),
	"magic_t2": preload("res://scripts/towers/visuals/by_id/magic_t2_visual.gd"),
	"magic_t3": preload("res://scripts/towers/visuals/by_id/magic_t3_visual.gd"),
	"muck_t1": preload("res://scripts/towers/visuals/by_id/muck_t1_visual.gd"),
	"muck_t2": preload("res://scripts/towers/visuals/by_id/muck_t2_visual.gd"),
	"muck_t3": preload("res://scripts/towers/visuals/by_id/muck_t3_visual.gd"),
	"mushroom_t1": preload("res://scripts/towers/visuals/by_id/mushroom_t1_visual.gd"),
	"mushroom_t2": preload("res://scripts/towers/visuals/by_id/mushroom_t2_visual.gd"),
	"mushroom_t3": preload("res://scripts/towers/visuals/by_id/mushroom_t3_visual.gd"),
	"nature_t1": preload("res://scripts/towers/visuals/by_id/nature_t1_visual.gd"),
	"nature_t2": preload("res://scripts/towers/visuals/by_id/nature_t2_visual.gd"),
	"nature_t3": preload("res://scripts/towers/visuals/by_id/nature_t3_visual.gd"),
	"neutral_cannon_tower": preload("res://scripts/towers/visuals/by_id/neutral_cannon_tower_visual.gd"),
	"nova_t1": preload("res://scripts/towers/visuals/by_id/nova_t1_visual.gd"),
	"nova_t2": preload("res://scripts/towers/visuals/by_id/nova_t2_visual.gd"),
	"nova_t3": preload("res://scripts/towers/visuals/by_id/nova_t3_visual.gd"),
	"oblivion_t1": preload("res://scripts/towers/visuals/by_id/oblivion_t1_visual.gd"),
	"oblivion_t2": preload("res://scripts/towers/visuals/by_id/oblivion_t2_visual.gd"),
	"oblivion_t3": preload("res://scripts/towers/visuals/by_id/oblivion_t3_visual.gd"),
	"periodic_t1": preload("res://scripts/towers/visuals/by_id/periodic_t1_visual.gd"),
	"poison_t1": preload("res://scripts/towers/visuals/by_id/poison_t1_visual.gd"),
	"poison_t2": preload("res://scripts/towers/visuals/by_id/poison_t2_visual.gd"),
	"poison_t3": preload("res://scripts/towers/visuals/by_id/poison_t3_visual.gd"),
	"polar_t1": preload("res://scripts/towers/visuals/by_id/polar_t1_visual.gd"),
	"polar_t2": preload("res://scripts/towers/visuals/by_id/polar_t2_visual.gd"),
	"polar_t3": preload("res://scripts/towers/visuals/by_id/polar_t3_visual.gd"),
	"pure_darkness": preload("res://scripts/towers/visuals/by_id/pure_darkness_visual.gd"),
	"pure_earth": preload("res://scripts/towers/visuals/by_id/pure_earth_visual.gd"),
	"pure_fire": preload("res://scripts/towers/visuals/by_id/pure_fire_visual.gd"),
	"pure_light": preload("res://scripts/towers/visuals/by_id/pure_light_visual.gd"),
	"pure_nature": preload("res://scripts/towers/visuals/by_id/pure_nature_visual.gd"),
	"pure_water": preload("res://scripts/towers/visuals/by_id/pure_water_visual.gd"),
	"quaker_t1": preload("res://scripts/towers/visuals/by_id/quaker_t1_visual.gd"),
	"quaker_t2": preload("res://scripts/towers/visuals/by_id/quaker_t2_visual.gd"),
	"quaker_t3": preload("res://scripts/towers/visuals/by_id/quaker_t3_visual.gd"),
	"quark_t1": preload("res://scripts/towers/visuals/by_id/quark_t1_visual.gd"),
	"quark_t2": preload("res://scripts/towers/visuals/by_id/quark_t2_visual.gd"),
	"quark_t3": preload("res://scripts/towers/visuals/by_id/quark_t3_visual.gd"),
	"roots_t1": preload("res://scripts/towers/visuals/by_id/roots_t1_visual.gd"),
	"roots_t2": preload("res://scripts/towers/visuals/by_id/roots_t2_visual.gd"),
	"roots_t3": preload("res://scripts/towers/visuals/by_id/roots_t3_visual.gd"),
	"tidal_t1": preload("res://scripts/towers/visuals/by_id/tidal_t1_visual.gd"),
	"tidal_t2": preload("res://scripts/towers/visuals/by_id/tidal_t2_visual.gd"),
	"tidal_t3": preload("res://scripts/towers/visuals/by_id/tidal_t3_visual.gd"),
	"trickery_t1": preload("res://scripts/towers/visuals/by_id/trickery_t1_visual.gd"),
	"trickery_t2": preload("res://scripts/towers/visuals/by_id/trickery_t2_visual.gd"),
	"trickery_t3": preload("res://scripts/towers/visuals/by_id/trickery_t3_visual.gd"),
	"vapor_t1": preload("res://scripts/towers/visuals/by_id/vapor_t1_visual.gd"),
	"vapor_t2": preload("res://scripts/towers/visuals/by_id/vapor_t2_visual.gd"),
	"vapor_t3": preload("res://scripts/towers/visuals/by_id/vapor_t3_visual.gd"),
	"voodoo_t1": preload("res://scripts/towers/visuals/by_id/voodoo_t1_visual.gd"),
	"voodoo_t2": preload("res://scripts/towers/visuals/by_id/voodoo_t2_visual.gd"),
	"voodoo_t3": preload("res://scripts/towers/visuals/by_id/voodoo_t3_visual.gd"),
	"water_t1": preload("res://scripts/towers/visuals/by_id/water_t1_visual.gd"),
	"water_t2": preload("res://scripts/towers/visuals/by_id/water_t2_visual.gd"),
	"water_t3": preload("res://scripts/towers/visuals/by_id/water_t3_visual.gd"),
	"well_t1": preload("res://scripts/towers/visuals/by_id/well_t1_visual.gd"),
	"well_t2": preload("res://scripts/towers/visuals/by_id/well_t2_visual.gd"),
	"well_t3": preload("res://scripts/towers/visuals/by_id/well_t3_visual.gd"),
	"windstorm_t1": preload("res://scripts/towers/visuals/by_id/windstorm_t1_visual.gd"),
	"windstorm_t2": preload("res://scripts/towers/visuals/by_id/windstorm_t2_visual.gd"),
	"windstorm_t3": preload("res://scripts/towers/visuals/by_id/windstorm_t3_visual.gd"),
	"zealot_t1": preload("res://scripts/towers/visuals/by_id/zealot_t1_visual.gd"),
	"zealot_t2": preload("res://scripts/towers/visuals/by_id/zealot_t2_visual.gd"),
	"zealot_t3": preload("res://scripts/towers/visuals/by_id/zealot_t3_visual.gd"),
}

# Shared visual-type family fallbacks. Used only when no BY_ID entry exists.
const VISUALS := {
	"acid_vat": preload("res://scripts/towers/visuals/fallback/acid_vat_tower_visual.gd"),
	"basic": preload("res://scripts/towers/visuals/fallback/basic_tower_visual.gd"),
	"bio_vine": preload("res://scripts/towers/visuals/fallback/bio_vine_tower_visual.gd"),
	"cannon": preload("res://scripts/towers/visuals/fallback/cannon_tower_visual.gd"),
	"chaos_orb": preload("res://scripts/towers/visuals/fallback/chaos_orb_tower_visual.gd"),
	"crystal_emitter": preload("res://scripts/towers/visuals/fallback/crystal_emitter_tower_visual.gd"),
	"dual_nozzle": preload("res://scripts/towers/visuals/fallback/dual_nozzle_tower_visual.gd"),
	"ember_bloom": preload("res://scripts/towers/visuals/fallback/ember_bloom_tower_visual.gd"),
	"forge_anvil": preload("res://scripts/towers/visuals/fallback/forge_anvil_tower_visual.gd"),
	"furnace": preload("res://scripts/towers/visuals/fallback/furnace_tower_visual.gd"),
	"gold_refinery": preload("res://scripts/towers/visuals/fallback/gold_refinery_tower_visual.gd"),
	"golem_body": preload("res://scripts/towers/visuals/fallback/golem_body_tower_visual.gd"),
	"hail_crystal": preload("res://scripts/towers/visuals/fallback/hail_crystal_tower_visual.gd"),
	"heavy_mortar": preload("res://scripts/towers/visuals/fallback/heavy_mortar_tower_visual.gd"),
	"hydro_cannon": preload("res://scripts/towers/visuals/fallback/hydro_cannon_tower_visual.gd"),
	"lightning": preload("res://scripts/towers/visuals/fallback/lightning_tower_visual.gd"),
	"particle_accel": preload("res://scripts/towers/visuals/fallback/particle_accel_tower_visual.gd"),
	"prism_lens": preload("res://scripts/towers/visuals/fallback/prism_lens_tower_visual.gd"),
	"rail_laser": preload("res://scripts/towers/visuals/fallback/rail_laser_tower_visual.gd"),
	"root_cage": preload("res://scripts/towers/visuals/fallback/root_cage_tower_visual.gd"),
	"seismic_drill": preload("res://scripts/towers/visuals/fallback/seismic_drill_tower_visual.gd"),
	"solar_bloom": preload("res://scripts/towers/visuals/fallback/solar_bloom_tower_visual.gd"),
	"spore_cap": preload("res://scripts/towers/visuals/fallback/spore_cap_tower_visual.gd"),
	"steam_boiler": preload("res://scripts/towers/visuals/fallback/steam_boiler_tower_visual.gd"),
	"stone_bastion": preload("res://scripts/towers/visuals/fallback/stone_bastion_tower_visual.gd"),
	"storm_turbine": preload("res://scripts/towers/visuals/fallback/storm_turbine_tower_visual.gd"),
	"strike_blades": preload("res://scripts/towers/visuals/fallback/strike_blades_tower_visual.gd"),
	"support_halo": preload("res://scripts/towers/visuals/fallback/support_halo_tower_visual.gd"),
	"tar_pool": preload("res://scripts/towers/visuals/fallback/tar_pool_tower_visual.gd"),
	"toxin_vial": preload("res://scripts/towers/visuals/fallback/toxin_vial_tower_visual.gd"),
	"tri_reactor": preload("res://scripts/towers/visuals/fallback/tri_reactor_tower_visual.gd"),
	"trickery": preload("res://scripts/towers/visuals/fallback/trickery_tower_visual.gd"),
	"void_flower": preload("res://scripts/towers/visuals/fallback/void_flower_tower_visual.gd"),
	"void_orb": preload("res://scripts/towers/visuals/fallback/void_orb_tower_visual.gd"),
	"void_vortex": preload("res://scripts/towers/visuals/fallback/void_vortex_tower_visual.gd"),
	"voodoo_totem": preload("res://scripts/towers/visuals/fallback/voodoo_totem_tower_visual.gd"),
}

static func get_visual_script(tower_id: String, visual_type: String) -> Script:
	if BY_ID.has(tower_id):
		return BY_ID[tower_id]
	return VISUALS.get(visual_type, VISUALS.get("basic"))
